services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.app.dev
    ports:
      - "5100:5100"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - ./app/.env