FROM node:20-slim AS builder

WORKDIR /app

# Install build tools
RUN apt-get update && apt-get install -y python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

# Copy package files
COPY prisma ./prisma
COPY package*.json ./

RUN npm install --legacy-peer-deps

# Copy source
COPY . .
RUN rm -rf .next

# Generate Prisma client inside container for ARM64
# ENV PRISMA_CLIENT_ENGINE_TYPE=binary
# ENV PRISMA_ENGINES_USE_BINARY_TARGETS=1
# ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
# RUN npx prisma generate --schema=./prisma/schema.prisma

RUN npm run build


FROM node:20-slim AS runner

WORKDIR /app

# Copy only what’s needed from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public

EXPOSE 5100

CMD ["npm", "start"]
