services:
  filmino:
    container_name: filmino-app
    build:
      context: .
      dockerfile: Dockerfile.app.prod
    ports:
      - "6050:5100"
    volumes:
      - .:/app
      - /node_modules
      - /.next
    environment:
      - NODE_ENV=production
      - DB_URL_PRISMA=${DB_URL}
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: filmino-db
    restart: always
    ports:
      - "6051:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin
    container_name: filmino-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "6052:80"
    depends_on:
      - db


volumes:
  db_data: