FROM node:20-slim AS builder

# Set working directory
WORKDIR /app

# Install dependencies only (to leverage Docker cache)
COPY package*.json ./
RUN npm i

# Copy the full source
COPY . .

# Remove any old builds
RUN rm -rf .next

# Build Next.js
RUN npm run build


FROM node:20-slim AS runner

WORKDIR /app

# Copy only the necessary files from builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

# Install only production dependencies
RUN npm ci --only=production && npm cache clean --force

# Expose port for Next.js
EXPOSE 5100

# Start Next.js
CMD ["npm", "start"]
