services:
  filmino:
    container_name: filmino-app
    image: lmerta/filmino-app:latest
    platform: linux/arm64/v8
    ports:
      - "6050:5100"
    environment:
      - NODE_ENV=production
      - DB_URL_PRISMA=${DB_URL}
    env_file:
      - .env