services:
  filmino:
    container_name: filmino-app
    build:
      context: .
      dockerfile: Dockerfile.app.dev
    ports:
      - "5100:5100"
    volumes:
      - .:/app
      - /node_modules
      - /.next
    environment:
      - NODE_ENV=development
      - DB_URL_PRISMA=${DB_URL}
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: filmino-db
    restart: always
    ports:
      - "5200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: filmino-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5300:80"
    depends_on:
      - db


volumes:
  db_data: