name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile.app.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filmino-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/filmino-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/filmino-app:buildcache,mode=max
         
      - name: Setup SSH key
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy files to home server
        run: |
          rsync -az -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ deploy@mertalukas.cz:/www/deploy/filmino

      - name: Create .env file on server
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT_INT }}
          DB_URL: mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT_INT }}/${{ secrets.DB_NAME }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_BASE_API_URL: ${{ secrets.NEXT_PUBLIC_BASE_API_URL }}
          NEXT_PUBLIC_BASE_HOST_URL: ${{ secrets.NEXT_PUBLIC_BASE_HOST_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_API_READ_KEY: ${{ secrets.TMDB_API_READ_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@mertalukas.cz "cat > /www/deploy/filmino/app/.env <<EOL
          DB_HOST=${DB_HOST}
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_NAME=${DB_NAME}
          DB_PORT=${DB_PORT}
          DB_URL=${DB_URL}
          PRISMA_ENGINES_USE_BINARY_TARGETS=1
          PRISMA_CLIENT_ENGINE_TYPE=binary
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
          GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
          GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
          NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
          NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}
          NEXT_PUBLIC_BASE_HOST_URL=${NEXT_PUBLIC_BASE_HOST_URL}
          TMDB_API_KEY=${TMDB_API_KEY}
          TMDB_API_READ_KEY=${TMDB_API_READ_KEY}
          EOL"

      - name: Run make up-prod on home server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@mertalukas.cz << EOF
            cd /www/deploy/filmino

            echo "⬇️ Pulling images from Docker Hub..."
            cd app
            docker compose -f docker-compose-prod.yml pull
            cd ..

            echo "♻️ Restarting services..."
            sudo make up-prod
          EOF
